#!/usr/bin/env bash
# Transfers a file from our client to a server

if [[ $1 ]] && [[ $2 ]] && [[ $3 ]] && [[ $4 ]]; then
	echo "$1" "$3"@"$2"
	scp -T -i "$4" "$1" "$3"@"$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
