#!/usr/bin/env bash
# service (init) must say that nginx is not running ← for real
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
