#!/usr/bin/env bash
trap 'catch_term' SIGTERM

catch_term() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

trap 'catch_int' SIGINT

catch_int() {
	echo "Y U no love me?!"
}

trap 'catch_quit' SIGQUIT

catch_quit() {
	rm /var/run/myscript.pid
	exit
}


echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
