#!/usr/bin/env bash
# manage manage_process daemon


case $1 in

	start)
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		pkill -f manage_my_process &> /dev/null
		;;
	restart)
		rm /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		pkill -f manage_my_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac	
