#!/usr/bin/env bash
# manage manage_process daemon


case $1 in

	start)
		./manage_my_process &
		sudo bash -c "echo $$ > /var/run/my_process.pid"
		echo "manage_my_process started"
		;;
	stop)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		pkill -f manage_my_process
		;;
	restart)
		pkill -f manage_my_process
		rm /var/run/my_process.pid
		./manage_my_process &
		sudo bash -c "echo $$ > /var/run/my_process.pid"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac	
