#!/usr/bin/env bash
# displays To infinity and beyond indefinitely

trap 'prnt' SIGTERM

prnt() {
	echo "I am invincible!!!"
}

i=1
while [ "$i" -lt 2 ]; do
	echo "To infinity and beyond"
	sleep 2
done
