#!/usr/bin/env bash
# Run nginx as non-root user nginx
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/ /var/run/ /var/log/nginx
pkill apache2
sudo -u nginx service nginx restart
